//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------


namespace Compliance.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_RiskAssessmentCategoryState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("opc_riskassessmentcategory")]
	public partial class opc_RiskAssessmentCategory : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public opc_RiskAssessmentCategory() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "opc_riskassessmentcategory";
		
		public const string EntitySchemaName = "opc_RiskAssessmentCategory";
		
		public const string PrimaryIdAttribute = "opc_riskassessmentcategoryid";
		
		public const string PrimaryNameAttribute = "opc_name";
		
		public const string EntityLogicalCollectionName = "opc_riskassessmentcategories";
		
		public const string EntitySetName = "opc_riskassessmentcategories";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// The actual risk appetite
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_actualriskappetite")]
		public Microsoft.Xrm.Sdk.EntityReference opc_ActualRiskAppetite
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("opc_actualriskappetite");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_ActualRiskAppetite");
				this.SetAttributeValue("opc_actualriskappetite", value);
				this.OnPropertyChanged("opc_ActualRiskAppetite");
			}
		}
		
		/// <summary>
		/// Indicates which user initiated the bypass for the suggested risk appetite
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_bypassinitiatedby")]
		public Microsoft.Xrm.Sdk.EntityReference opc_BypassInitiatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("opc_bypassinitiatedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_BypassInitiatedBy");
				this.SetAttributeValue("opc_bypassinitiatedby", value);
				this.OnPropertyChanged("opc_BypassInitiatedBy");
			}
		}
		
		/// <summary>
		/// The rationale explaining why the suggested risk appetite was bypassed
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_bypassrationale")]
		public string opc_BypassRationale
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("opc_bypassrationale");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_BypassRationale");
				this.SetAttributeValue("opc_bypassrationale", value);
				this.OnPropertyChanged("opc_BypassRationale");
			}
		}
		
		/// <summary>
		/// Indicates if the suggested risk appetite is bypassed
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_bypasssuggestedriskappetite")]
		public System.Nullable<bool> opc_BypassSuggestedRiskAppetite
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("opc_bypasssuggestedriskappetite");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_BypassSuggestedRiskAppetite");
				this.SetAttributeValue("opc_bypasssuggestedriskappetite", value);
				this.OnPropertyChanged("opc_BypassSuggestedRiskAppetite");
			}
		}
		
		/// <summary>
		/// Required name field
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_name")]
		public string opc_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("opc_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_Name");
				this.SetAttributeValue("opc_name", value);
				this.OnPropertyChanged("opc_Name");
			}
		}
		
		/// <summary>
		/// The risk assessment associated with this risk category
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_riskassessment")]
		public Microsoft.Xrm.Sdk.EntityReference opc_RiskAssessment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("opc_riskassessment");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_RiskAssessment");
				this.SetAttributeValue("opc_riskassessment", value);
				this.OnPropertyChanged("opc_RiskAssessment");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_riskassessmentcategoryid")]
		public System.Nullable<System.Guid> opc_RiskAssessmentCategoryId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("opc_riskassessmentcategoryid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_RiskAssessmentCategoryId");
				this.SetAttributeValue("opc_riskassessmentcategoryid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("opc_RiskAssessmentCategoryId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_riskassessmentcategoryid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.opc_RiskAssessmentCategoryId = value;
			}
		}
		
		/// <summary>
		/// The template for this risk assessment category
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_riskassessmentcategorytemplate")]
		public Microsoft.Xrm.Sdk.EntityReference opc_RiskAssessmentCategoryTemplate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("opc_riskassessmentcategorytemplate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_RiskAssessmentCategoryTemplate");
				this.SetAttributeValue("opc_riskassessmentcategorytemplate", value);
				this.OnPropertyChanged("opc_RiskAssessmentCategoryTemplate");
			}
		}
		
		/// <summary>
		/// The type of risk assessment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_riskassessmenttype")]
		public Microsoft.Xrm.Sdk.EntityReference opc_RiskAssessmentType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("opc_riskassessmenttype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_RiskAssessmentType");
				this.SetAttributeValue("opc_riskassessmenttype", value);
				this.OnPropertyChanged("opc_RiskAssessmentType");
			}
		}
		
		/// <summary>
		/// The sequence that this risk assessment category appears
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_sequence")]
		public System.Nullable<int> opc_Sequence
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("opc_sequence");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_Sequence");
				this.SetAttributeValue("opc_sequence", value);
				this.OnPropertyChanged("opc_Sequence");
			}
		}
		
		/// <summary>
		/// The suggested risk appetite
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_suggestedriskappetite")]
		public Microsoft.Xrm.Sdk.EntityReference opc_SuggestedRiskAppetite
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("opc_suggestedriskappetite");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_SuggestedRiskAppetite");
				this.SetAttributeValue("opc_suggestedriskappetite", value);
				this.OnPropertyChanged("opc_SuggestedRiskAppetite");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Risk Assessment Category
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Compliance.EarlyBound.opc_RiskAssessmentCategoryState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Compliance.EarlyBound.opc_RiskAssessmentCategoryState)(System.Enum.ToObject(typeof(Compliance.EarlyBound.opc_RiskAssessmentCategoryState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Risk Assessment Category
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual opc_RiskAssessmentCategoryStatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((opc_RiskAssessmentCategoryStatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N opc_RiskAssessmentDefinition_RiskAssessme
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("opc_RiskAssessmentDefinition_RiskAssessme")]
		public System.Collections.Generic.IEnumerable<Compliance.EarlyBound.opc_RiskAssessmentDefinition> opc_RiskAssessmentDefinition_RiskAssessme
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Compliance.EarlyBound.opc_RiskAssessmentDefinition>("opc_RiskAssessmentDefinition_RiskAssessme", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_RiskAssessmentDefinition_RiskAssessme");
				this.SetRelatedEntities<Compliance.EarlyBound.opc_RiskAssessmentDefinition>("opc_RiskAssessmentDefinition_RiskAssessme", null, value);
				this.OnPropertyChanged("opc_RiskAssessmentDefinition_RiskAssessme");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_opc_riskassessmentcategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_opc_riskassessmentcategory")]
		public Compliance.EarlyBound.BusinessUnit business_unit_opc_riskassessmentcategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.BusinessUnit>("business_unit_opc_riskassessmentcategory", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_opc_riskassessmentcategory_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_opc_riskassessmentcategory_createdby")]
		public Compliance.EarlyBound.SystemUser lk_opc_riskassessmentcategory_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.SystemUser>("lk_opc_riskassessmentcategory_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_opc_riskassessmentcategory_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_opc_riskassessmentcategory_createdonbehalfby")]
		public Compliance.EarlyBound.SystemUser lk_opc_riskassessmentcategory_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.SystemUser>("lk_opc_riskassessmentcategory_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_opc_riskassessmentcategory_createdonbehalfby");
				this.SetRelatedEntity<Compliance.EarlyBound.SystemUser>("lk_opc_riskassessmentcategory_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_opc_riskassessmentcategory_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_opc_riskassessmentcategory_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_opc_riskassessmentcategory_modifiedby")]
		public Compliance.EarlyBound.SystemUser lk_opc_riskassessmentcategory_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.SystemUser>("lk_opc_riskassessmentcategory_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_opc_riskassessmentcategory_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_opc_riskassessmentcategory_modifiedonbehalfby")]
		public Compliance.EarlyBound.SystemUser lk_opc_riskassessmentcategory_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.SystemUser>("lk_opc_riskassessmentcategory_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_opc_riskassessmentcategory_modifiedonbehalfby");
				this.SetRelatedEntity<Compliance.EarlyBound.SystemUser>("lk_opc_riskassessmentcategory_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_opc_riskassessmentcategory_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 opc_opc_riskassessmentcategorytemplate_opc_riskassessmentcategory_RiskAssessmentCategoryTemplate
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_riskassessmentcategorytemplate")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("opc_opc_riskassessmentcategorytemplate_opc_riskassessmentcategory_RiskAssessmentC" +
			"ategoryTemplate")]
		public Compliance.EarlyBound.opc_RiskAssessmentCategoryTemplate opc_opc_riskassessmentcategorytemplate_opc_riskassessmentcategory_RiskAssessmentCategoryTemplate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.opc_RiskAssessmentCategoryTemplate>("opc_opc_riskassessmentcategorytemplate_opc_riskassessmentcategory_RiskAssessmentC" +
						"ategoryTemplate", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_opc_riskassessmentcategorytemplate_opc_riskassessmentcategory_RiskAssessmentC" +
						"ategoryTemplate");
				this.SetRelatedEntity<Compliance.EarlyBound.opc_RiskAssessmentCategoryTemplate>("opc_opc_riskassessmentcategorytemplate_opc_riskassessmentcategory_RiskAssessmentC" +
						"ategoryTemplate", null, value);
				this.OnPropertyChanged("opc_opc_riskassessmentcategorytemplate_opc_riskassessmentcategory_RiskAssessmentC" +
						"ategoryTemplate");
			}
		}
		
		/// <summary>
		/// N:1 opc_opc_riskassessmenttype_opc_riskassessmentcategory_RiskAssessmentType
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_riskassessmenttype")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("opc_opc_riskassessmenttype_opc_riskassessmentcategory_RiskAssessmentType")]
		public Compliance.EarlyBound.opc_RiskAssessmentType opc_opc_riskassessmenttype_opc_riskassessmentcategory_RiskAssessmentType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.opc_RiskAssessmentType>("opc_opc_riskassessmenttype_opc_riskassessmentcategory_RiskAssessmentType", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_opc_riskassessmenttype_opc_riskassessmentcategory_RiskAssessmentType");
				this.SetRelatedEntity<Compliance.EarlyBound.opc_RiskAssessmentType>("opc_opc_riskassessmenttype_opc_riskassessmentcategory_RiskAssessmentType", null, value);
				this.OnPropertyChanged("opc_opc_riskassessmenttype_opc_riskassessmentcategory_RiskAssessmentType");
			}
		}
		
		/// <summary>
		/// N:1 opc_RiskAssessmentCategory_ActualRiskAppe
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_actualriskappetite")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("opc_RiskAssessmentCategory_ActualRiskAppe")]
		public Compliance.EarlyBound.opc_RiskAppetite opc_RiskAssessmentCategory_ActualRiskAppe
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.opc_RiskAppetite>("opc_RiskAssessmentCategory_ActualRiskAppe", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_RiskAssessmentCategory_ActualRiskAppe");
				this.SetRelatedEntity<Compliance.EarlyBound.opc_RiskAppetite>("opc_RiskAssessmentCategory_ActualRiskAppe", null, value);
				this.OnPropertyChanged("opc_RiskAssessmentCategory_ActualRiskAppe");
			}
		}
		
		/// <summary>
		/// N:1 opc_RiskAssessmentCategory_BypassInitiate
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_bypassinitiatedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("opc_RiskAssessmentCategory_BypassInitiate")]
		public Compliance.EarlyBound.SystemUser opc_RiskAssessmentCategory_BypassInitiate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.SystemUser>("opc_RiskAssessmentCategory_BypassInitiate", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_RiskAssessmentCategory_BypassInitiate");
				this.SetRelatedEntity<Compliance.EarlyBound.SystemUser>("opc_RiskAssessmentCategory_BypassInitiate", null, value);
				this.OnPropertyChanged("opc_RiskAssessmentCategory_BypassInitiate");
			}
		}
		
		/// <summary>
		/// N:1 opc_RiskAssessmentCategory_RiskAssessment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_riskassessment")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("opc_RiskAssessmentCategory_RiskAssessment")]
		public Compliance.EarlyBound.opc_RiskAssessment opc_RiskAssessmentCategory_RiskAssessment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.opc_RiskAssessment>("opc_RiskAssessmentCategory_RiskAssessment", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_RiskAssessmentCategory_RiskAssessment");
				this.SetRelatedEntity<Compliance.EarlyBound.opc_RiskAssessment>("opc_RiskAssessmentCategory_RiskAssessment", null, value);
				this.OnPropertyChanged("opc_RiskAssessmentCategory_RiskAssessment");
			}
		}
		
		/// <summary>
		/// N:1 opc_RiskAssessmentCategory_SuggestedRiskA
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opc_suggestedriskappetite")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("opc_RiskAssessmentCategory_SuggestedRiskA")]
		public Compliance.EarlyBound.opc_RiskAppetite opc_RiskAssessmentCategory_SuggestedRiskA
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.opc_RiskAppetite>("opc_RiskAssessmentCategory_SuggestedRiskA", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("opc_RiskAssessmentCategory_SuggestedRiskA");
				this.SetRelatedEntity<Compliance.EarlyBound.opc_RiskAppetite>("opc_RiskAssessmentCategory_SuggestedRiskA", null, value);
				this.OnPropertyChanged("opc_RiskAssessmentCategory_SuggestedRiskA");
			}
		}
		
		/// <summary>
		/// N:1 team_opc_riskassessmentcategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_opc_riskassessmentcategory")]
		public Compliance.EarlyBound.Team team_opc_riskassessmentcategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.Team>("team_opc_riskassessmentcategory", null);
			}
		}
		
		/// <summary>
		/// N:1 user_opc_riskassessmentcategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_opc_riskassessmentcategory")]
		public Compliance.EarlyBound.SystemUser user_opc_riskassessmentcategory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Compliance.EarlyBound.SystemUser>("user_opc_riskassessmentcategory", null);
			}
		}
	}
}