declare namespace Form.opc_complaint.Main {
  namespace Information {
    namespace Tabs {
      interface tab_allegations extends Xrm.SectionCollectionBase {
        get(name: "section_allegations"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_documents extends Xrm.SectionCollectionBase {
        get(name: "section_documents"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_general extends Xrm.SectionCollectionBase {
        get(name: "section_complainant"): Xrm.PageSection;
        get(name: "section_general"): Xrm.PageSection;
        get(name: "section_notes_activities"): Xrm.PageSection;
        get(name: "section_respondent"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_issues extends Xrm.SectionCollectionBase {
        get(name: "section_issues"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_recommendations extends Xrm.SectionCollectionBase {
        get(name: "section_recommendations"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_reminders extends Xrm.SectionCollectionBase {
        get(name: "section_reminders"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_risk_assessments extends Xrm.SectionCollectionBase {
        get(name: "section_risk_assessments"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "opc_acceptancedate"): Xrm.DateAttribute;
      get(name: "opc_accountid"): Xrm.LookupAttribute<"account">;
      get(name: "opc_actualriskappetitevalue"): Xrm.NumberAttribute;
      get(name: "opc_closereason"): Xrm.OptionSetAttribute<opc_closereason> | null;
      get(name: "opc_complainant"): Xrm.LookupAttribute<"contact">;
      get(name: "opc_complainantlegalrepresentative"): Xrm.LookupAttribute<"contact">;
      get(name: "opc_complainantlegalrepresentativefirm"): Xrm.LookupAttribute<"account">;
      get(name: "opc_complainantperceivedpriorities"): Xrm.MultiSelectOptionSetAttribute<opc_perceivedpriorities>;
      get(name: "opc_complainantrep"): Xrm.LookupAttribute<"contact">;
      get(name: "opc_complainantreportdrafted"): Xrm.OptionSetAttribute<boolean> | null;
      get(name: "opc_complaintreceiveddate"): Xrm.DateAttribute;
      get(name: "opc_erapproval"): Xrm.OptionSetAttribute<opc_erapproval> | null;
      get(name: "opc_erdisposition"): Xrm.OptionSetAttribute<opc_erdisposition> | null;
      get(name: "opc_erofficer"): Xrm.LookupAttribute<"systemuser">;
      get(name: "opc_escalationapproved"): Xrm.OptionSetAttribute<boolean> | null;
      get(name: "opc_intakedisposition"): Xrm.OptionSetAttribute<opc_intakedisposition> | null;
      get(name: "opc_intakeofficer"): Xrm.LookupAttribute<"systemuser">;
      get(name: "opc_lastmilestone"): Xrm.OptionSetAttribute<opc_complaintmilestone>;
      get(name: "opc_legislation"): Xrm.LookupAttribute<"opc_legislation">;
      get(name: "opc_memberofparliamentinvolved"): Xrm.Attribute<any>;
      get(name: "opc_multiplecomplaintstrategy"): Xrm.OptionSetAttribute<opc_multiplecomplaintstrategy>;
      get(name: "opc_nextstep"): Xrm.OptionSetAttribute<opc_nextstep> | null;
      get(name: "opc_number"): Xrm.Attribute<string>;
      get(name: "opc_opcpriorityid"): Xrm.LookupAttribute<"opc_opcpriority">;
      get(name: "opc_reasontorequirefurtherinvestigation"): Xrm.MultiSelectOptionSetAttribute<opc_reasontorequirefurtherinvestigation> | null;
      get(name: "opc_recommendtoregistrar"): Xrm.OptionSetAttribute<opc_yesorno> | null;
      get(name: "opc_reportredactor"): Xrm.LookupAttribute<"systemuser"> | null;
      get(name: "opc_reportrequested"): Xrm.OptionSetAttribute<boolean> | null;
      get(name: "opc_representativeauthorizationprovided"): Xrm.OptionSetAttribute<boolean> | null;
      get(name: "opc_requiresfurtherinvestigation"): Xrm.OptionSetAttribute<boolean> | null;
      get(name: "opc_resolution"): Xrm.MultiSelectOptionSetAttribute<opc_complaintresolution> | null;
      get(name: "opc_respondentandcomplainantrelationship"): Xrm.OptionSetAttribute<opc_respondentandcomplainantrelationship>;
      get(name: "opc_respondentlegalrepresentative"): Xrm.LookupAttribute<"contact">;
      get(name: "opc_respondentlegalrepresentativefirm"): Xrm.LookupAttribute<"account">;
      get(name: "opc_respondentreportdrafted"): Xrm.OptionSetAttribute<boolean> | null;
      get(name: "opc_respondentrepresentative"): Xrm.LookupAttribute<"contact">;
      get(name: "opc_sendcloseletter"): Xrm.OptionSetAttribute<boolean> | null;
      get(name: "opc_sladate"): Xrm.DateAttribute;
      get(name: "opc_source"): Xrm.OptionSetAttribute<opc_complaintsource>;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: "statuscode"): Xrm.OptionSetAttribute<opc_complaint_statuscode>;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "SubgridControl1570455352989"): Xrm.SubGridControl<"opc_issue">;
      get(name: "SubgridControl1570455487438"): Xrm.SubGridControl<"opc_recommendation">;
      get(name: "header_opc_acceptancedate"): Xrm.DateControl;
      get(name: "header_opc_erofficer"): Xrm.LookupControl<"systemuser">;
      get(name: "header_opc_intakeofficer"): Xrm.LookupControl<"systemuser">;
      get(name: "header_opc_lastmilestone"): Xrm.OptionSetControl<opc_complaintmilestone>;
      get(name: "header_opc_number"): Xrm.StringControl;
      get(name: "header_opc_sladate"): Xrm.DateControl;
      get(name: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "header_process_opc_accountid"): Xrm.LookupControl<"account"> | null;
      get(name: "header_process_opc_closereason"): Xrm.OptionSetControl<opc_closereason> | null;
      get(name: "header_process_opc_closereason_1"): Xrm.OptionSetControl<opc_closereason> | null;
      get(name: "header_process_opc_closereason_2"): Xrm.OptionSetControl<opc_closereason> | null;
      get(name: "header_process_opc_closereason_3"): Xrm.OptionSetControl<opc_closereason> | null;
      get(name: "header_process_opc_complainant"): Xrm.LookupControl<"contact"> | null;
      get(name: "header_process_opc_complainantreportdrafted"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_opc_erapproval"): Xrm.OptionSetControl<opc_erapproval> | null;
      get(name: "header_process_opc_erapproval_1"): Xrm.OptionSetControl<opc_erapproval> | null;
      get(name: "header_process_opc_erdisposition"): Xrm.OptionSetControl<opc_erdisposition> | null;
      get(name: "header_process_opc_escalationapproved"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_opc_intakedisposition"): Xrm.OptionSetControl<opc_intakedisposition> | null;
      get(name: "header_process_opc_intakedisposition_1"): Xrm.OptionSetControl<opc_intakedisposition> | null;
      get(name: "header_process_opc_legislation"): Xrm.LookupControl<"opc_legislation"> | null;
      get(name: "header_process_opc_nextstep"): Xrm.OptionSetControl<opc_nextstep> | null;
      get(name: "header_process_opc_nextstep_1"): Xrm.OptionSetControl<opc_nextstep> | null;
      get(name: "header_process_opc_reasontorequirefurtherinvestigation"): Xrm.MultiSelectOptionSetControl<opc_reasontorequirefurtherinvestigation> | null;
      get(name: "header_process_opc_recommendtoregistrar"): Xrm.OptionSetControl<opc_yesorno> | null;
      get(name: "header_process_opc_reportredactor"): Xrm.LookupControl<"systemuser"> | null;
      get(name: "header_process_opc_reportrequested"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_opc_representativeauthorizationprovided"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_opc_requiresfurtherinvestigation"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_opc_resolution"): Xrm.MultiSelectOptionSetControl<opc_complaintresolution> | null;
      get(name: "header_process_opc_respondentandcomplainantrelationship"): Xrm.OptionSetControl<opc_respondentandcomplainantrelationship> | null;
      get(name: "header_process_opc_respondentreportdrafted"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_opc_sendcloseletter"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_opc_sendcloseletter_1"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_opc_sendcloseletter_2"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_opc_sendcloseletter_3"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_opc_sendcloseletter_4"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_opc_sendcloseletter_5"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_statuscode"): Xrm.OptionSetControl<opc_complaint_statuscode>;
      get(name: "notescontrol"): Xrm.BaseControl;
      get(name: "opc_accountid"): Xrm.LookupControl<"account">;
      get(name: "opc_actualriskappetitevalue"): Xrm.NumberControl;
      get(name: "opc_complainant"): Xrm.LookupControl<"contact">;
      get(name: "opc_complainantlegalrepresentative"): Xrm.LookupControl<"contact">;
      get(name: "opc_complainantlegalrepresentativefirm"): Xrm.LookupControl<"account">;
      get(name: "opc_complainantperceivedpriorities"): Xrm.MultiSelectOptionSetControl<opc_perceivedpriorities>;
      get(name: "opc_complainantrep"): Xrm.LookupControl<"contact">;
      get(name: "opc_complaintreceiveddate"): Xrm.DateControl;
      get(name: "opc_legislation"): Xrm.LookupControl<"opc_legislation">;
      get(name: "opc_memberofparliamentinvolved"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "opc_multiplecomplaintstrategy"): Xrm.OptionSetControl<opc_multiplecomplaintstrategy>;
      get(name: "opc_opcpriorityid"): Xrm.LookupControl<"opc_opcpriority">;
      get(name: "opc_respondentandcomplainantrelationship"): Xrm.OptionSetControl<opc_respondentandcomplainantrelationship>;
      get(name: "opc_respondentlegalrepresentative"): Xrm.LookupControl<"contact">;
      get(name: "opc_respondentlegalrepresentativefirm"): Xrm.LookupControl<"account">;
      get(name: "opc_respondentrepresentative"): Xrm.LookupControl<"contact">;
      get(name: "opc_source"): Xrm.OptionSetControl<opc_complaintsource>;
      get(name: "subgrid_allegations"): Xrm.SubGridControl<"opc_allegation">;
      get(name: "subgrid_documents"): Xrm.SubGridControl<"sharepointdocument">;
      get(name: "subgrid_industries"): Xrm.BaseControl;
      get(name: "subgrid_reminders"): Xrm.SubGridControl<"opc_reminder">;
      get(name: "subgrid_risk_assessments"): Xrm.SubGridControl<"opc_riskassessment">;
      get(name: "subgrid_topics"): Xrm.BaseControl;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "tab_allegations"): Xrm.PageTab<Tabs.tab_allegations>;
      get(name: "tab_documents"): Xrm.PageTab<Tabs.tab_documents>;
      get(name: "tab_general"): Xrm.PageTab<Tabs.tab_general>;
      get(name: "tab_issues"): Xrm.PageTab<Tabs.tab_issues>;
      get(name: "tab_recommendations"): Xrm.PageTab<Tabs.tab_recommendations>;
      get(name: "tab_reminders"): Xrm.PageTab<Tabs.tab_reminders>;
      get(name: "tab_risk_assessments"): Xrm.PageTab<Tabs.tab_risk_assessments>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "opc_acceptancedate"): Xrm.DateAttribute;
    getAttribute(attributeName: "opc_accountid"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "opc_actualriskappetitevalue"): Xrm.NumberAttribute;
    getAttribute(attributeName: "opc_closereason"): Xrm.OptionSetAttribute<opc_closereason> | null;
    getAttribute(attributeName: "opc_complainant"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "opc_complainantlegalrepresentative"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "opc_complainantlegalrepresentativefirm"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "opc_complainantperceivedpriorities"): Xrm.MultiSelectOptionSetAttribute<opc_perceivedpriorities>;
    getAttribute(attributeName: "opc_complainantrep"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "opc_complainantreportdrafted"): Xrm.OptionSetAttribute<boolean> | null;
    getAttribute(attributeName: "opc_complaintreceiveddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "opc_erapproval"): Xrm.OptionSetAttribute<opc_erapproval> | null;
    getAttribute(attributeName: "opc_erdisposition"): Xrm.OptionSetAttribute<opc_erdisposition> | null;
    getAttribute(attributeName: "opc_erofficer"): Xrm.LookupAttribute<"systemuser">;
    getAttribute(attributeName: "opc_escalationapproved"): Xrm.OptionSetAttribute<boolean> | null;
    getAttribute(attributeName: "opc_intakedisposition"): Xrm.OptionSetAttribute<opc_intakedisposition> | null;
    getAttribute(attributeName: "opc_intakeofficer"): Xrm.LookupAttribute<"systemuser">;
    getAttribute(attributeName: "opc_lastmilestone"): Xrm.OptionSetAttribute<opc_complaintmilestone>;
    getAttribute(attributeName: "opc_legislation"): Xrm.LookupAttribute<"opc_legislation">;
    getAttribute(attributeName: "opc_memberofparliamentinvolved"): Xrm.Attribute<any>;
    getAttribute(attributeName: "opc_multiplecomplaintstrategy"): Xrm.OptionSetAttribute<opc_multiplecomplaintstrategy>;
    getAttribute(attributeName: "opc_nextstep"): Xrm.OptionSetAttribute<opc_nextstep> | null;
    getAttribute(attributeName: "opc_number"): Xrm.Attribute<string>;
    getAttribute(attributeName: "opc_opcpriorityid"): Xrm.LookupAttribute<"opc_opcpriority">;
    getAttribute(attributeName: "opc_reasontorequirefurtherinvestigation"): Xrm.MultiSelectOptionSetAttribute<opc_reasontorequirefurtherinvestigation> | null;
    getAttribute(attributeName: "opc_recommendtoregistrar"): Xrm.OptionSetAttribute<opc_yesorno> | null;
    getAttribute(attributeName: "opc_reportredactor"): Xrm.LookupAttribute<"systemuser"> | null;
    getAttribute(attributeName: "opc_reportrequested"): Xrm.OptionSetAttribute<boolean> | null;
    getAttribute(attributeName: "opc_representativeauthorizationprovided"): Xrm.OptionSetAttribute<boolean> | null;
    getAttribute(attributeName: "opc_requiresfurtherinvestigation"): Xrm.OptionSetAttribute<boolean> | null;
    getAttribute(attributeName: "opc_resolution"): Xrm.MultiSelectOptionSetAttribute<opc_complaintresolution> | null;
    getAttribute(attributeName: "opc_respondentandcomplainantrelationship"): Xrm.OptionSetAttribute<opc_respondentandcomplainantrelationship>;
    getAttribute(attributeName: "opc_respondentlegalrepresentative"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "opc_respondentlegalrepresentativefirm"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "opc_respondentreportdrafted"): Xrm.OptionSetAttribute<boolean> | null;
    getAttribute(attributeName: "opc_respondentrepresentative"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "opc_sendcloseletter"): Xrm.OptionSetAttribute<boolean> | null;
    getAttribute(attributeName: "opc_sladate"): Xrm.DateAttribute;
    getAttribute(attributeName: "opc_source"): Xrm.OptionSetAttribute<opc_complaintsource>;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: "statuscode"): Xrm.OptionSetAttribute<opc_complaint_statuscode>;
    getAttribute(attributeName: string): undefined;
    getControl(controlName: "SubgridControl1570455352989"): Xrm.SubGridControl<"opc_issue">;
    getControl(controlName: "SubgridControl1570455487438"): Xrm.SubGridControl<"opc_recommendation">;
    getControl(controlName: "header_opc_acceptancedate"): Xrm.DateControl;
    getControl(controlName: "header_opc_erofficer"): Xrm.LookupControl<"systemuser">;
    getControl(controlName: "header_opc_intakeofficer"): Xrm.LookupControl<"systemuser">;
    getControl(controlName: "header_opc_lastmilestone"): Xrm.OptionSetControl<opc_complaintmilestone>;
    getControl(controlName: "header_opc_number"): Xrm.StringControl;
    getControl(controlName: "header_opc_sladate"): Xrm.DateControl;
    getControl(controlName: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "header_process_opc_accountid"): Xrm.LookupControl<"account"> | null;
    getControl(controlName: "header_process_opc_closereason"): Xrm.OptionSetControl<opc_closereason> | null;
    getControl(controlName: "header_process_opc_closereason_1"): Xrm.OptionSetControl<opc_closereason> | null;
    getControl(controlName: "header_process_opc_closereason_2"): Xrm.OptionSetControl<opc_closereason> | null;
    getControl(controlName: "header_process_opc_closereason_3"): Xrm.OptionSetControl<opc_closereason> | null;
    getControl(controlName: "header_process_opc_complainant"): Xrm.LookupControl<"contact"> | null;
    getControl(controlName: "header_process_opc_complainantreportdrafted"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_opc_erapproval"): Xrm.OptionSetControl<opc_erapproval> | null;
    getControl(controlName: "header_process_opc_erapproval_1"): Xrm.OptionSetControl<opc_erapproval> | null;
    getControl(controlName: "header_process_opc_erdisposition"): Xrm.OptionSetControl<opc_erdisposition> | null;
    getControl(controlName: "header_process_opc_escalationapproved"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_opc_intakedisposition"): Xrm.OptionSetControl<opc_intakedisposition> | null;
    getControl(controlName: "header_process_opc_intakedisposition_1"): Xrm.OptionSetControl<opc_intakedisposition> | null;
    getControl(controlName: "header_process_opc_legislation"): Xrm.LookupControl<"opc_legislation"> | null;
    getControl(controlName: "header_process_opc_nextstep"): Xrm.OptionSetControl<opc_nextstep> | null;
    getControl(controlName: "header_process_opc_nextstep_1"): Xrm.OptionSetControl<opc_nextstep> | null;
    getControl(controlName: "header_process_opc_reasontorequirefurtherinvestigation"): Xrm.MultiSelectOptionSetControl<opc_reasontorequirefurtherinvestigation> | null;
    getControl(controlName: "header_process_opc_recommendtoregistrar"): Xrm.OptionSetControl<opc_yesorno> | null;
    getControl(controlName: "header_process_opc_reportredactor"): Xrm.LookupControl<"systemuser"> | null;
    getControl(controlName: "header_process_opc_reportrequested"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_opc_representativeauthorizationprovided"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_opc_requiresfurtherinvestigation"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_opc_resolution"): Xrm.MultiSelectOptionSetControl<opc_complaintresolution> | null;
    getControl(controlName: "header_process_opc_respondentandcomplainantrelationship"): Xrm.OptionSetControl<opc_respondentandcomplainantrelationship> | null;
    getControl(controlName: "header_process_opc_respondentreportdrafted"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_opc_sendcloseletter"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_opc_sendcloseletter_1"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_opc_sendcloseletter_2"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_opc_sendcloseletter_3"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_opc_sendcloseletter_4"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_opc_sendcloseletter_5"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_statuscode"): Xrm.OptionSetControl<opc_complaint_statuscode>;
    getControl(controlName: "notescontrol"): Xrm.BaseControl;
    getControl(controlName: "opc_accountid"): Xrm.LookupControl<"account">;
    getControl(controlName: "opc_actualriskappetitevalue"): Xrm.NumberControl;
    getControl(controlName: "opc_complainant"): Xrm.LookupControl<"contact">;
    getControl(controlName: "opc_complainantlegalrepresentative"): Xrm.LookupControl<"contact">;
    getControl(controlName: "opc_complainantlegalrepresentativefirm"): Xrm.LookupControl<"account">;
    getControl(controlName: "opc_complainantperceivedpriorities"): Xrm.MultiSelectOptionSetControl<opc_perceivedpriorities>;
    getControl(controlName: "opc_complainantrep"): Xrm.LookupControl<"contact">;
    getControl(controlName: "opc_complaintreceiveddate"): Xrm.DateControl;
    getControl(controlName: "opc_legislation"): Xrm.LookupControl<"opc_legislation">;
    getControl(controlName: "opc_memberofparliamentinvolved"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "opc_multiplecomplaintstrategy"): Xrm.OptionSetControl<opc_multiplecomplaintstrategy>;
    getControl(controlName: "opc_opcpriorityid"): Xrm.LookupControl<"opc_opcpriority">;
    getControl(controlName: "opc_respondentandcomplainantrelationship"): Xrm.OptionSetControl<opc_respondentandcomplainantrelationship>;
    getControl(controlName: "opc_respondentlegalrepresentative"): Xrm.LookupControl<"contact">;
    getControl(controlName: "opc_respondentlegalrepresentativefirm"): Xrm.LookupControl<"account">;
    getControl(controlName: "opc_respondentrepresentative"): Xrm.LookupControl<"contact">;
    getControl(controlName: "opc_source"): Xrm.OptionSetControl<opc_complaintsource>;
    getControl(controlName: "subgrid_allegations"): Xrm.SubGridControl<"opc_allegation">;
    getControl(controlName: "subgrid_documents"): Xrm.SubGridControl<"sharepointdocument">;
    getControl(controlName: "subgrid_industries"): Xrm.BaseControl;
    getControl(controlName: "subgrid_reminders"): Xrm.SubGridControl<"opc_reminder">;
    getControl(controlName: "subgrid_risk_assessments"): Xrm.SubGridControl<"opc_riskassessment">;
    getControl(controlName: "subgrid_topics"): Xrm.BaseControl;
    getControl(controlName: string): undefined;
  }
}
