//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound.Actions
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/opc/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("opc_complaintcheckcomplainantemailaddresses")]
	public partial class opc_complaintcheckcomplainantemailaddressesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public opc_complaintcheckcomplainantemailaddressesResponse()
		{
		}
		
		public bool HasEmail
		{
			get
			{
				if (this.Results.Contains("HasEmail"))
				{
					return ((bool)(this.Results["HasEmail"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}