//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/opc/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("opc_IndividualComplaintActionMovetoStage")]
	public partial class opc_IndividualComplaintActionMovetoStageResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public opc_IndividualComplaintActionMovetoStageResponse()
		{
		}
	}
}