//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/opc/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("opc_generatedocumentfromtemplate")]
	public partial class opc_generatedocumentfromtemplateRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string SharePointSiteUrl
		{
			get
			{
				if (this.Parameters.Contains("SharePointSiteUrl"))
				{
					return ((string)(this.Parameters["SharePointSiteUrl"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SharePointSiteUrl"] = value;
			}
		}
		
		public string DocumentName
		{
			get
			{
				if (this.Parameters.Contains("DocumentName"))
				{
					return ((string)(this.Parameters["DocumentName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DocumentName"] = value;
			}
		}
		
		public string AccessToken
		{
			get
			{
				if (this.Parameters.Contains("AccessToken"))
				{
					return ((string)(this.Parameters["AccessToken"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["AccessToken"] = value;
			}
		}
		
		public string CaseFolderPath
		{
			get
			{
				if (this.Parameters.Contains("CaseFolderPath"))
				{
					return ((string)(this.Parameters["CaseFolderPath"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CaseFolderPath"] = value;
			}
		}
		
		public string TemplatePath
		{
			get
			{
				if (this.Parameters.Contains("TemplatePath"))
				{
					return ((string)(this.Parameters["TemplatePath"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TemplatePath"] = value;
			}
		}
		
		public string XMLData
		{
			get
			{
				if (this.Parameters.Contains("XMLData"))
				{
					return ((string)(this.Parameters["XMLData"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["XMLData"] = value;
			}
		}
		
		public opc_generatedocumentfromtemplateRequest()
		{
			this.RequestName = "opc_generatedocumentfromtemplate";
			this.SharePointSiteUrl = default(string);
			this.DocumentName = default(string);
			this.AccessToken = default(string);
			this.CaseFolderPath = default(string);
			this.TemplatePath = default(string);
			this.XMLData = default(string);
		}
	}
}