name: Lint TypeScript

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint TypeScript
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Compliance.WebResources
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: npm run lint
        run: npm run lint
