pool:
  vmImage: 'vs2017-win2016'

steps:
- task: opc-cpvp.opc-powerapps-buildtools.opc-powerapps-tool-installer.PowerAppsToolInstaller@1
  displayName: 'OPC - PowerApps Tool Installer '

- task: opc-cpvp.opc-powerapps-buildtools.opc-powerapps-create-environment.PowerAppsCreateEnvironment@1
  displayName: 'OPC - PowerApps Create Environment '
  inputs:
    PowerAppsAdminCredentials: 'PowerApps Admin'
    DomainName: '$(DomainName)'
    DisplayName: '$(DisplayName)'
