//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contactmsdyn_orgchangestatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ignore = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoFeedback = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotatCompany = 1,
	}
}