//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum DuplicateRuleStatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Publishing = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unpublished = 0,
	}
}