//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum DuplicateRuleBaseEntityTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccessRequestDocument = 10086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Account = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ACIViewMapper = 8040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActionCard = 9962,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActionCardType = 9983,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActionCardUserSettings = 9973,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActionCardUserState = 9968,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activity = 4200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActivityParty = 135,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Address = 1071,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AdvancedSimilarityRule = 9949,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIBuilderDataset = 10067,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIBuilderDatasetFile = 10068,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIBuilderDatasetRecord = 10069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIBuilderDatasetsContainer = 10070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIBuilderFile = 10071,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIBuilderFileAttachedData = 10072,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIConfiguration = 402,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIFormProcessingDocument = 10073,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIModel = 401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIObjectDetectionBoundingBox = 10076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIObjectDetectionImage = 10074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIObjectDetectionImageMapping = 10077,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIObjectDetectionLabel = 10075,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AITemplate = 400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AllegationConcern = 10087,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AllegationType = 10088,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnalysisComponent = 10079,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnalysisJob = 10080,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnalysisResult = 10081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnalysisResultDetail = 10082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Announcement = 132,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnnualFiscalCalendar = 2000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppConfigMaster = 9011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppConfiguration = 9012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppConfigurationInstance = 9013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplicationFile = 4707,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplicationRibbons = 1120,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplicationUser = 10021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppModuleComponent = 9007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppModuleMetadata = 8700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppModuleMetadataAsyncOperation = 8702,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppModuleMetadataDependency = 8701,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppModuleRoles = 9009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Article = 127,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ArticleComment = 1082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ArticleTemplate = 1016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attachment_1001 = 1001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attachment_1002 = 1002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attribute = 9808,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributeMap = 4601,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Auditing = 4567,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AuthorizationServer = 1094,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AzureServiceConnection = 9936,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BotContent = 10037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkDeleteFailure = 4425,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkDeleteOperation = 4424,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessDataLocalizedLabel = 4232,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessProcessFlowInstance = 4725,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessUnit = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessUnitMap = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Calendar = 4003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CalendarRule = 4004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CallbackRegistration = 301,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CanvasApp = 300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CanvasAppExtendedMetadata = 10031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CascadeGrantRevokeAccessRecordsTracker = 10018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CascadeGrantRevokeAccessVersionTracker = 10019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Catalog = 10054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CatalogAssignment = 10055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Category = 9959,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChannelAccessProfile = 3005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChannelAccessProfileRule = 9400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChannelAccessProfileRuleItem = 9401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChannelProperty = 1236,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChannelPropertyGroup = 1234,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Chatbot = 10039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Chatbotsubcomponent = 10040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChecklistResponse = 10089,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChecklistType = 10090,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Clientupdate = 36,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ColumnMapping = 4417,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Comment = 8005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Complaint = 10091,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ComponentLayer = 10005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ComponentLayerDataSource = 10006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connection = 3234,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConnectionReference = 10035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConnectionRole = 3231,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConnectionRoleObjectTypeCode = 3233,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connector = 372,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConversationTranscript = 10038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Currency = 9105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomAPI = 10057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomAPIRequestParameter = 10058,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomAPIResponseProperty = 10059,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomControl = 9753,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomControlDefaultConfig = 9755,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomControlResource = 9754,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerRelationship = 4502,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dataflow = 418,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataImport = 4410,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataLakeFolder = 10014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataLakeFolderPermission = 10015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataLakeWorkspace = 10016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataLakeWorkspacePermission = 10017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataMap = 4411,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataPerformanceDashboard = 4450,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DelveActionHub = 9961,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dependency = 7105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DependencyFeature = 7108,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DependencyNode = 7106,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DisplayString = 4102,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DisplayStringMap = 4101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DispositionAction = 10092,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DispositionReason = 10093,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DocumentLocation = 9508,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DocumentSuggestions = 1189,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DocumentTemplate = 9940,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DuplicateDetectionRule = 4414,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DuplicateRecord = 4415,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DuplicateRuleCondition = 4416,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailHash = 4023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailSearch = 4299,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailServerProfile = 9605,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailSignature = 9997,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailTemplate = 2010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entity = 9800,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityAnalyticsConfig = 430,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityImageConfiguration = 432,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityKey = 9810,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityMap = 4600,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRelationship = 9811,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EnvironmentVariableDefinition = 380,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EnvironmentVariableValue = 381,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Event = 10094,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExchangeSyncIdMapping = 4120,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExpanderEvent = 4711,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExpiredProcess = 955,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExportSolutionUpload = 10010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExternalParty = 3008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExternalPartyItem = 9987,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Feedback = 9958,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldPermission = 1201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldSecurityProfile = 1200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldSharing = 44,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FileAttachment = 55,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FilterTemplate = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FixedMonthlyFiscalCalendar = 2004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FlowSession = 4720,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Follow = 8003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GlobalSearchConfiguration = 54,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Goal = 9600,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GoalMetric = 9603,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HelpPage = 10036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HierarchyRule = 8840,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HierarchySecurityConfiguration = 9919,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HolidayWrapper = 9996,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImageAttributeConfiguration = 431,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImageDescriptor = 1007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportData = 4413,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportEntityMapping = 4428,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportJob = 9107,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportLog = 4423,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportSourceFile = 4412,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IndexedArticle = 126,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IndividualComplaint = 10095,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Industry = 10096,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IntegrationStatus = 3000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InteractionforEmail = 9986,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalAddress = 1003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalCatalogAssignment = 10056,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InterProcessLock = 4011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidDependency = 7107,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Issue = 10097,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ISVConfig = 4705,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticle = 9953,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleCategory = 9960,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleImage = 10050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleTemplate = 10053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleViews = 9955,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeBaseRecord = 9930,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeFederatedArticle = 10047,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeFederatedArticleIncident = 10048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeInteractionInsight = 10051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeSearchInsight = 10052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeSearchModel = 9947,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Language = 9957,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LanguageProvisioningState = 9875,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Legislation = 10098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letter = 4207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		License = 2027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Like = 8006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ListValueMapping = 4418,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LocalConfigStore = 9201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LookupMapping = 4419,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mailbox = 9606,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailboxAutoTrackingFolder = 9608,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailboxStatistics = 9607,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailboxTrackingCategory = 9609,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailMergeTemplate = 9106,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ManagedProperty = 9812,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MetadataDifference = 4231,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MobileOfflineProfile = 9866,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MobileOfflineProfileItem = 9867,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MobileOfflineProfileItemAssociation = 9868,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ModeldrivenApp = 9006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ModelDrivenAppComponentNode = 10026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ModelDrivenAppComponentNodesEdge = 10025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ModelDrivenAppElement = 10024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ModelDrivenAppSetting = 10027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ModelDrivenAppUserSetting = 10028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MonthlyFiscalCalendar = 2003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MultiEntitySearch = 9910,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MultiSelectOptionValue = 9912,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NavigationSetting = 9900,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NewProcess = 950,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonRelationalDataSource = 10065,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Note = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Notification_10099 = 10099,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Notification_4110 = 4110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ODatav4DataSource = 10032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OfficeDocument = 4490,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OfficeGraphDocument = 9950,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OfflineCommandDefinition = 9870,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OPCPriority = 10100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptionSet = 9809,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organization = 1019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationDataSyncSubscription = 10062,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationDataSyncSubscriptionEntity = 10063,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationInsightsMetric = 9699,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationInsightsNotification = 9690,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationSetting = 10029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationStatistic = 4708,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationUI = 1021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Owner = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OwnerMapping = 4420,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Package = 10007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PartnerApplication = 1095,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PDFSetting = 10044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PersonalDocumentTemplate = 9941,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PluginAssembly = 4605,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PluginTraceLog = 4619,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PluginType = 4602,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PluginTypeStatistic = 4603,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Position = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Post = 8000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostRegarding = 8002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostRole = 8001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PrincipalSyncAttributeMap = 1404,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Privilege = 1023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PrivilegeObjectTypeCode = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Process = 4703,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProcessConfiguration = 9650,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProcessDependency = 4704,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProcessLog = 4706,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProcessSession = 4710,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProcessStage = 4724,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProcessStageParameter = 10033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProcessTrigger = 4712,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProvisionLanguageForUser = 10013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Publisher = 7101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PublisherAddress = 7102,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuarterlyFiscalCalendar = 2002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuestionTemplate = 10101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuestionType = 10102,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Queue = 2020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueItem = 2029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueItemCount = 2023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueMemberCount = 2024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Recommendation = 10103,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecordCreationandUpdateRule = 9300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecordCreationandUpdateRuleItem = 9301,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurrenceRule = 4250,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringAppointment = 4251,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelationshipAttribute = 9814,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelationshipEntity = 9813,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelationshipRole = 4500,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelationshipRoleMap = 4501,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reminder = 10104,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReplicationBacklog = 1140,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Report = 9100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportLink = 9104,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportRelatedCategory = 9102,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportRelatedEntity = 9101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportVisibility = 9103,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RevokeInheritedAccessRecordsTracker = 90001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonClientMetadata = 4579,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonCommand = 1116,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonContextGroup = 1115,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonDifference = 1130,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonMetadataToProcess = 9880,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonRule = 1117,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonTabToCommandMapping = 1113,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RichTextAttachment = 10064,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RiskAppetite = 10105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RiskAssessment = 10106,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RiskAssessmentCategory = 10107,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RiskAssessmentCategoryTemplate = 10108,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RiskAssessmentDefinition = 10109,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RiskAssessmentDefinitionTemplate = 10110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RiskAssessmentFactorTemplate = 10111,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RiskAssessmentType = 10112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RoleTemplate = 1037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RollupField = 9604,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RollupJob = 9511,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RollupProperties = 9510,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RollupQuery = 9602,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RoutingRuleSet = 8181,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RuleItem = 8199,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RuntimeDependency = 7200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SavedOrganizationInsightsConfiguration = 1309,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SavedView = 4230,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessage = 4606,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageFilter = 4607,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessagePair = 4613,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageProcessingStep = 4608,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageProcessingStepImage = 4615,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageProcessingStepSecureConfiguration = 4616,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageRequest = 4609,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageRequestField = 4614,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageResponse = 4610,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageResponseField = 4611,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Searchprovider = 10049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SearchTelemetry = 10066,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SecurityRole = 1036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SemiannualFiscalCalendar = 2001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceConfiguration = 10045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceEndpoint = 4618,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServicePlan = 101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SettingDefinition = 10030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SharePointData = 9509,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SharepointDocument = 9507,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SharePointSite = 9502,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SimilarityRule = 9951,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SiteMap = 4709,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLA = 9750,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLAItem = 9751,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLAKPI = 10046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLAKPIInstance = 9752,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialActivity = 4216,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialInsightsConfiguration = 1300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialProfile = 99,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Solution = 7100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionComponent = 7103,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionComponentAttributeConfiguration = 10002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionComponentConfiguration = 10003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionComponentDataSource = 10012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionComponentDefinition = 7104,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionComponentRelationshipConfiguration = 10004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionComponentSummary = 10011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionHealthRule = 10083,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionHealthRuleArgument = 10084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionHealthRuleSet = 10085,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionHistory = 10000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionHistoryData = 9890,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionHistoryDataSource = 10001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StageSolutionUpload = 10009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StatusMap = 1075,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StringMap = 1043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Subject = 129,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Subscription = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SubscriptionClients = 1072,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SubscriptionManuallyTrackedObject = 37,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SubscriptionStatisticOffline = 45,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SubscriptionStatisticOutlook = 46,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SubscriptionSyncEntryOffline = 47,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SubscriptionSyncEntryOutlook = 48,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SubscriptionSynchronizationInformation = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SuggestionCardTemplate = 1190,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SyncAttributeMapping = 1401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SyncAttributeMappingProfile = 1400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SyncError = 9869,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemApplicationMetadata = 7000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemChart = 1111,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemForm = 1030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemJob = 4700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemUserAuthorizationChangeTracker = 60,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemUserBusinessUnitEntityMap = 42,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemUserManagerMap = 51,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemUserPrincipal = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Team = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TeamMobileOfflineProfileMembership = 10060,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TeamProfiles = 1203,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TeamSyncAttributeMappingProfiles = 1403,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Teamtemplate = 92,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Territory = 2013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TextAnalyticsEntityMapping = 9945,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Theme_10113 = 10113,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Theme_2015 = 2015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeStampDateMapping = 9932,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeZoneDefinition = 4810,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeZoneLocalizedName = 4812,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeZoneRule = 4811,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Topic = 10114,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Trace = 8050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TraceAssociation = 8051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TraceRegarding = 8052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Trackinginformationfordeletedentities = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TransformationMapping = 4426,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TransformationParameterMapping = 4427,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TranslationProcess = 951,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnresolvedAddress = 2012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UntrackedEmail = 4220,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserApplicationMetadata = 7001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserChart = 1112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserDashboard = 1031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserEntityInstanceData = 2501,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserEntityUISettings = 2500,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserFiscalCalendar = 1086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserMapping = 2016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserMobileOfflineProfileMembership = 10061,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserSearchFacet = 52,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserSettings = 150,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		View = 1039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		VirtualEntityDataProvider = 78,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		VirtualEntityDataSource = 85,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebResource = 9333,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebWizard = 4800,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebWizardAccessPrivilege = 4803,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WizardPage = 4802,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkflowBinary = 10034,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkflowWaitSubscription = 4702,
	}
}