//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_PerceivedPriorities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Acknowledgement = 533950001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Apology = 533950000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Calltoaction = 533950002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Compensation = 533950003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Court = 533950004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fineorpenalty = 533950006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fulfilloriginalrequestprovideallegedmissingdocuments = 533950005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reimbursement = 533950007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Timeliness = 533950008,
	}
}