//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_NextStep
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Discontinued = 924340004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolved = 924340001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Settled = 924340003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transfertoinvestigations = 924340000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Withdrawn = 924340002,
	}
}