//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_ERDisposition
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Discontinued = 533950003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolved = 533950001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnsuccessfulUnsuitable = 533950000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Withdrawn = 533950002,
	}
}