//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_ComplaintSource
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letter = 533950001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Onlinecorrespondence = 533950000,
	}
}