//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_ComplaintDisposition
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Discontinued = 924340000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Investigationcompleted = 924340001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nojurisidiction = 924340002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolvedatearlyresolution = 924340003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolvedatintake = 924340004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Settled = 924340005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unresponsiveinquirer = 924340006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Withdrawn = 924340007,
	}
}