//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_Jurisdictions
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Condominium_condocorporationoritsagent = 533950003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FirstNationbandcouncil = 533950004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Individual = 533950005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MUSHSector_municipalityuniversityschoolhospitals = 533950001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotforProfitorCharitableOrganization = 533950002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OnlineorofflinenewspapermagazineradioorTVbroadcaster = 533950006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Politicalparty = 533950007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnderProvincialJurisdiction = 533950000,
	}
}