//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_eventStatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Open = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Scheduled = 4,
	}
}