//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_PreferredLanguage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		English = 924340000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		French = 924340001,
	}
}