//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_AllegationDisposition
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Acceptable = 924340000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolved = 924340005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unacceptable = 924340001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Withdrawn = 924340002,
	}
}