//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_ReasontoRequireFurtherInvestigation
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Complexity = 533950001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Distributionoffiles = 533950005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Highrankfile = 533950002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Litigiousindividual = 533950003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Time = 533950006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unresponsiverespondent = 533950004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Volumeofpages = 533950000,
	}
}