//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_complaintStatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Createdinerror = 924340015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Declined = 924340001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Duplicate = 924340002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Investigationcompleted = 924340007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Investigationdiscontinued = 924340014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		New = 924340010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Redirected = 924340006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolved = 924340004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Settled = 924340005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Underearlyresolution = 924340012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Underinitialassessment = 924340011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Underinvestigation = 924340013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Underregistrarreview_Active_924340017 = 924340017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Underregistrarreview_Active_924340022 = 924340022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Underreportredaction = 924340019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Underreviewforassignment = 924340018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Underreviewforclosure = 924340021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Underreviewforescalation = 924340020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnsuitableUnsuccessful = 924340016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Withdrawn = 924340003,
	}
}