//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum opc_intakedisposition
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Close = 924340003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Declinetoinvestigate = 924340002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MovetoEarlyResolution = 924340000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MovetoInvestigation = 924340001,
	}
}