//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SocialProfile_Community
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facebook = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Twitter = 2,
	}
}