//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUserPreferredPhoneCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HomePhone = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MainPhone = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MobilePhone = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OtherPhone = 2,
	}
}