//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUserPreferredAddressCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailingAddress = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OtherAddress = 2,
	}
}