//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum TeamTeamType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AADOfficeGroup = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AADSecurityGroup = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Access = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Owner = 0,
	}
}