//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum UserSettingsEntityFormMode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Edit = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organizationdefault = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Readoptimized = 1,
	}
}