//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum UserSettingsDefaultSearchExperience
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Categorizedsearch = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customsearch = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Relevancesearch = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Uselastsearch = 2,
	}
}