//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace Compliance.EarlyBound.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum UserSettingsReportScriptErrors
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AskmeforpermissiontosendanerrorreporttoMicrosoft = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutomaticallysendanerrorreporttoMicrosoftwithoutaskingmeforpermission = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NeversendanerrorreporttoMicrosoftaboutMicrosoftDynamics365 = 3,
	}
}